spring:
  application:
    name: ordermanager
  datasource:
    initialize: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
aws:
  dynamodb:
    endpoint: http://localhost:8000
    region: us-east-1
    credentials:
      access-key: FAKE
      secret-key: FAKE
logging:
  level:
    root: INFO
    com.example.ordermanager: DEBUG
